package bpsk_tx_pkg;

// Built-in Self-Test (BIST) parameters for Tx control  
// // // localparam BIST_MIN_PKT_GAP = 1024;

// Fixed point parameters for all signed data interfaces between all DSP 
// blocks in the transmitter. 
//           FIR_IF        CIC_IF        DUC_IF
// +--------+  \/   +-----+  \/   +-----+  \/   +-----+
// | Mapper | ====> | FIR | ====> | CIC | ====> | DUC |
// +--------+       +-----+       +-----+       +-----+
localparam FIR_DATA_WIDTH  = 2;
localparam FIR_FIXED_WIDTH = 0;
localparam CIC_DATA_WIDTH  = 8;
localparam CIC_FIXED_WIDTH = 6;
localparam DUC_DATA_WIDTH  = 16;
localparam DUC_FIXED_WIDTH = 14;

localparam MAPPER_CLK_PER_SAMPLE = 20; // Defines samplerate generated by the mapper

// Input control of the tx control
typedef struct packed {
    logic bist_start;    // pulse, start BIST mode
} tx_ctrl_t;

// Output status of the tx control
typedef struct packed {
    logic bist_active;  // level, 1 while a run is sending packets or waiting out a gap
    logic bist_done;    // pulse, inform that the requested number of packets has been sent
} tx_status_t;

endpackage

